services:
  api:
    ports:
      # Exposes application port.
    - "9090:8000"
    build:
      context: .
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      MED_RAG_SERVER_RELOAD: "True"

  taskiq-worker:
    volumes:
      # Adds current directory as volume.
      - .:/app/src/
    command:
      - taskiq
      - worker
      - med_rag_server.tkq:broker
      # - --reload
